# File cấu hình Redis tùy chỉnh (redis.conf)

# Chỉ cho phép binding ở mọi địa chỉ IPv4 (Mặc định nó hay gắn ở 127.0.0.1, mình mở ra để dễ test từ bên ngoài)
bind 0.0.0.0

# Chạy ở cổng tùy chọn, ở đây thử đổi mặc định (6379) thành port khác đi
port 6379

# Đặt mật khẩu truy cập (Security)
requirepass myredissecret

# Cấu hình tần suất lưu dữ liệu xuống đĩa (Snapshots - RDB)
# Lưu sau 900 giây nếu có ít nhất 1 khóa (key) bị thay đổi
save 900 1

# Tắt chế độ log quá dài dòng (chỉ hiện notice hoặc warning)
loglevel notice